version: "3.8"
services:

  tomee:
    container_name: tomee-8.0.8-plus
#    build:
#      context: ./openmdx-example
#      dockerfile: ./Dockerfile
    image: "tomee:8.0.8-plus"
    ports:
      - "8484:8080"
      - "8100:8100"
    environment:
      - JPDA_ADDRESS=*:8100
      - JPDA_TRANSPORT=dt_socket
    command: "/usr/local/tomee/bin/catalina.sh jpda run"
    volumes:
      - ./tomee/conf/tomee.xml:$CATALINA_BASE/conf/tomee.xml
      - ./tomee/conf/tomcat-users.xml:$CATALINA_BASE/conf/tomcat-users.xml
      - ./tomee/db/driver/postgresql-42.2.22.jar:$CATALINA_BASE/lib/postgresql-42.2.22.jar
      - ./tomee/webapps/manager/META-INF/context.xml:$CATALINA_BASE/webapps/manager/META-INF/context.xml
      - ./workshop/build/deployment-unit/openmdx-workshop-rest.war:$CATALINA_BASE/webapps/openmdx-workshop-rest.war

  postgres:
    container_name: postgres-14
    image: "postgres:14"
    ports:
      - "5432:5432"
    volumes:
      - ./_tmp_/pgdata:/var/lib/postgresql_14/wksp
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_DB=$PG_DB
